In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\AZER\Downloads\housing.csv\housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB
None

In [4]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [5]:
df.fillna({'total_bedrooms':df['total_bedrooms'].mean()},inplace=True)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [6]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

What we have done so far is called data preparation.We loaded data,checked null values and filled with mean values. This is used for preventing data leakage in training model.

In [7]:

X = df.drop(columns=['median_house_value'])
y = df['median_house_value']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


X_train = pd.get_dummies(X_train, columns=['ocean_proximity'])
X_test = pd.get_dummies(X_test, columns=['ocean_proximity'])

X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

In this step we divite dataframe into 2 parts: train and test. get_dummies fucntion allow us to transfer values in dataframe into 0 and 1

In [8]:
from sklearn.preprocessing import RobustScaler
rs = RobustScaler()
features = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
            'total_bedrooms', 'population', 'households', 'median_income']
X_train[features] = rs.fit_transform(X_train[features])
X_test[features] = rs.transform(X_test[features])

In this part we used robust scaling for detecting and removing outliers from features. This may lead to getting big values after training values or other words data leakage

In [9]:
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error
sgd = SGDRegressor(max_iter=1000, tol=1e-3, random_state=42,penalty='l2',alpha=0.001)
sgd.fit(X_train,y_train)

SGDRegressor(alpha=0.001, random_state=42)

In this step we trained model with gradient descent.

In [10]:
y_pred = sgd.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print(f"RMSE: {rmse}")

RMSE: 70172.36957340344

In [11]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print(f"RMSE: {rmse}")

RMSE: 49178.123815595725

In [12]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print(f"R2 score: {r2}")

R2 score: 0.815440224984672

In [15]:
import plotly.express as px
import plotly.graph_objects as go

In [16]:
residuals = y_test - y_pred

df_res = pd.DataFrame({
    "Predicted": y_pred,
    "Residuals": residuals
})

fig = px.scatter(
    df_res,
    x="Predicted",
    y="Residuals",
    title="Residual Plot (Interactive)",
    opacity=0.7
)


fig.add_hline(y=0, line_dash="dash", line_color="red")

fig.show()

In [17]:
fig = px.histogram(
    df_res,
    x="Residuals",
    nbins=30,
    title="Residuals Distribution",
    opacity=0.75
)

fig.show()

In [18]:
fig = px.scatter(
    df_res,
    x="Predicted",
    y="Residuals",
    color=abs(df_res["Residuals"]),
    color_continuous_scale="RdBu",
    title="Residual Plot with Error Intensity",
    opacity=0.8
)

fig.add_hline(y=0, line_dash="dash")

fig.update_layout(
    coloraxis_colorbar_title="Error magnitude"
)

fig.show()